### PR TITLE
Add per-app config info to readme and changelog

### PR DESCRIPTION
**Pull request by sabondano**
Why:

* For devs to know how to use per-app config and to include per-app
config changes to changelog.

### CODE REVIEW

**Comment by sabondano** [comment]
@sntran anything else you can think of to get it ready for a new release?

**Comment by heymackey** [comment]
@sabondano Perhaps bumping [this version](https://github.com/sntran/ueberauth_auth0/blob/master/mix.exs#L4) in the changeset too?

**Comment by sntran** [comment]
Is there any difference between this PR and #65?

**Comment by sabondano** [comment]
> Is there any difference between this PR and #65?

This one updates readme and changelog. #65 doesn't have any commits. Thank you.

**Comment by achedeuzot** [comment]
This has been updated in the README. Thank @sabondano !

**Pull request closed without merging**
