### PR TITLE
chore(*): Bump version to 0.5.0

### PR DESCRIPTION
**Pull request by achedeuzot**
Hi there :)

I'm opening a version bump PR to push the latest changes into a hex release. Do you think you would have some time to do the releasing in the upcoming days @sntran or a way of allowing me to do it ? You can reach me on twitter with DMs under the same handle @achedeuzot if needed ;) 

Thanks a lot !

### CODE REVIEW

**Comment by achedeuzot** [comment]
Hi @sntran :) Any way we could go forward with this ? I'd like to further improve this module :)

**Comment by achedeuzot** [comment]
Hi @sntran , could you get back to me before the end of the month ? It's blocking some features I'd like to add to this module as well as some bug fixes that I need. 

I'd really like to be autonomous on this module (release, tests, ...) and get out of your way if you don't have the time to do it. Please get back to me so we can find a way that's OK for both.

**Comment by sntran** [comment]
Hi @achedeuzot !

Sorry for the lack of activity on my end!

If I transfer the repo to you, will you be able to do everything? Or do I need to also transfer Hex's ownership too?

**Comment by sntran** [comment]
I would also see @sobolevn 's opinion on the transfer, but not sure if he has time to look at any time soon.

**Comment by achedeuzot** [comment]
Hi @sntran , you'll need to transfer the repo, and I think the hex.pm ownership too so I can push releases.

In any case, the repo will just be redirected to the new one and won't disappear. I'll keep it public with the same Licence as yours was so if @sobolevn wants to discuss this later on, we can discuss through a github issue or you can contact me through whatever other means is good with you :)

**Comment by sntran** [comment]
GitHub does not let me transfer, since you already have a repo with the same name. I

**Comment by achedeuzot** [comment]
Oh sorry, I've deleted it now :)

**Comment by achedeuzot** [comment]
I have the same handle (@achedeuzot) on hex.pm (if that information helps ^^)

**Comment by sntran** [comment]
Alright, I have transferred the repo to you, and also added you as the owner of the hex's package.

**Comment by achedeuzot** [comment]
Perfect, thank you so much for your help @sntran  :)

**Comment by sntran** [comment]
Hi @achedeuzot, is there any reason that you removed me from the the hex's package?

**Comment by achedeuzot** [comment]
Hi @sntran, I was testing how this `hex.owner` stuff works. I've added you back :)

**Pull request merged**
